### ISSUE TITLE
Unicode characters failing paginate.py?

### ISSUE THREAD

**Issue by bbbradsmith** [pinobatch/thwaite-nes#6]
The following characters are generating an exception for me when building this:
tips.txt: 🏠,🚀
texts.txt: ©

```
py -3 tools/paginate.py --dte \
        -t cutscripts src/cutscripts.txt \
        -t tips src/tips.txt \
        -t text src/texts.txt \
        -o obj/nes/dtescripts.s
Traceback (most recent call last):
  File "tools/paginate.py", line 353, in <module>
    main()
  File "tools/paginate.py", line 305, in main
    pages = list(lines_to_docs(infp))
  File "tools/paginate.py", line 17, in lines_to_docs
    for line in lines:
  File "C:\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 98: character maps to <undefined>
make: *** [obj/nes/dtescripts.s] Error 1

py -3 tools/paginate.py --dte \
        -t cutscripts src/cutscripts.txt \
        -t tips src/tips.txt \
        -t text src/texts.txt \
        -o obj/nes/dtescripts.s
Traceback (most recent call last):
  File "tools/paginate.py", line 353, in <module>
    main()
  File "tools/paginate.py", line 306, in main
    parsed, ltc = parsefunc(pages)
  File "tools/paginate.py", line 116, in parse_text
    enc = "\n".join(lines).replace("il","\u01C1").encode("thwaite")
  File "C:\MinGW\msys\1.0\home\rainwarrior\thwaite-nes-master\tools\charset.py", line 37, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\xc2' in position 14: character maps to <undefined>
make: *** [obj/nes/dtescripts.s] Error 1
```

Am using Python 3 on Windows 10 using Make from the MinGW/MSYS shell, if any of that is relevant.

**Comment by pinobatch** [comment]
Does it still happen if you change the `open()` call on line 304 to explicitly specify UTF-8 encoding? The default character encoding may differ between Windows and Linux builds.
```
    with open(infilename, "r", encoding="utf-8") as infp:
```

**Comment by bbbradsmith** [comment]
I was just about to suggest that as a pull request, but when I went to edit you'd already done it. :>

**Comment by bbbradsmith** [comment]
AFAIK Python 3 is supposed to default to UTF-8 on Windows though? I'm kinda curious why this is a problem.

**Comment by bbbradsmith** [comment]
The encoding it's reporting is "cp1252"?

**Comment by bbbradsmith** [comment]
After looking it up I guess it's defined by the environment. I think I'm used to being explicit about encodings when using python for text parsing, so it was something I hadn't thought about or tested the default before.
